apiVersion: v1
kind: Service
metadata:
  name: elk-log
  labels:
    service: elk
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: serving
  - port: 9300
    name: node-to-node
  selector:
    service: elk